### ISSUE TITLE
Any plans to register an initial version?

### ISSUE THREAD

**Issue by VarLad** [paulgb/PenPlots.jl#6]
Since Pluto now has a built-in package manager, its a hassle to use PenPlots.jl without it being registered.

It'd be nice to have a 0.1 version registered for now

**Comment by fonsp** [comment]
@paulgb I'd be happy to register and do some maintenance if you like!

**Comment by paulgb** [comment]
@fonsp I'd gladly accept that! Just added you to the repo.

**Comment by fonsp** [comment]
Thanks Paul! https://github.com/JuliaRegistries/General/pull/54648

**Comment by fonsp** [comment]
Registered!
